/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from MathService.xml. ***/
/*===================================================*/
 
export MathService := MODULE
 
export t_AddThisRequest := record
	integer FirstNumber {xpath('FirstNumber')};
	integer SecondNumber {xpath('SecondNumber')};
end;
 
export t_AddThisResponse := record
	integer Answer {xpath('Answer')};
end;
 
end;
 
/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from MathService.xml. ***/
/*===================================================*/
 

